name: Build & Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        run: cd build && npm install
      - name: Build
        run: cd build && npm run build
      - name: Remove node modules
        run: cd build && rm -rf node_modules
      - name: Move static files
        run: |
          cd build;
          mv dist/* ../;
          cp src/flaglist.ts ../flaglist.d.ts;
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Remove files not pushed to output
        run: |
          rm -rf .github build/dist build/package-lock.json
      - name: Create Indexes
        uses: Exponential-Workload/create-index-action@master
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
